// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _Messages_added_fixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Messages_added_fixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202208022116562__Messages_added_fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
